pullRequests.frequency = "0 0 * * *" # Run daily at midnight
pullRequests.grouping = [
  { name = "patches", "title" = "Patch updates", "filter" = [{"version" = "patch"}] },
  { name = "minor", "title" = "Minor updates", "filter" = [{"version" = "minor"}] },
  { name = "major", "title" = "Major updates", "filter" = [{"version" = "major"}] },
  { name = "all", "title" = "Dependency updates", "filter" = [{"group" = "*"}] }
]

updates.ignore = [
  { groupId = "org.scala-lang", artifactId = "scala3-library" } # Managed specifically by the team
]

updates.limit = 5

commits.message = "chore(deps): update \${artifactName} from \${currentVersion} to \${nextVersion}"

postUpdateHooks = [
  {
    command = ["sbt", "dependencyLockWrite"],
    commitMessage = "chore(deps): update dependency lock file",
    groupId = "*"
  }
]
