POSTGRES_HOST = "localhost"
POSTGRES_HOST = ${?POSTGRES_HOST}
POSTGRES_PORT = 3210
POSTGRES_PORT = ${?POSTGRES_PORT}
POSTGRES_DB   = "ledger"
POSTGRES_DB   = ${?POSTGRES_DB}
POSTGRES_USER = "ledger"
POSTGRES_USER = ${?POSTGRES_USER}
POSTGRES_PASSWORD = "password"
POSTGRES_PASSWORD = ${?POSTGRES_PASSWORD}

http.host = "127.0.0.1"
http.host = ${?HTTP_HOST}
http.port = 8000
http.port = ${?HTTP_PORT}

PEKKO_REMOTE_HOSTNAME = "127.0.0.1"
PEKKO_REMOTE_HOSTNAME = ${?PEKKO_REMOTE_HOSTNAME}


include "event-journal.conf"

pekko {
  # Enable actor provisioning through Pekko Cluster
  actor.provider = cluster

  # Log level used by the configured loggers (see "loggers") as soon
  # as they have been started; before that, see "stdout-loglevel"
  # Options: OFF, ERROR, WARNING, INFO, DEBUG
  loglevel = "INFO"

  # Loggers to register at boot time (pekko.event.Logging$DefaultLogger logs to STDOUT)
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]

  # Filter of log events that is used by the LoggingAdapter before publishing log events to the eventStream.
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"

  actor {
    serializers {
      proto = "domain.ScalaPbSerializer"
    }
    serialization-bindings {
      "scalapb.GeneratedMessage" = proto
    }
  }
}


pekko.cluster {
  sharding {
    number-of-shards = 100
  }
  
  # The node joins itself to form a cluster of 1.
  seed-nodes = ["pekko://baseledger@"${PEKKO_REMOTE_HOSTNAME}":2551"]
  
  # Automatically down nodes (irrelevant for a 1-node cluster, but keeps it clean)
  downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  shutdown-after-unsuccessful-join-seed-nodes = 60s
  
  # Start the Shard Region immediately without waiting for other nodes
  min-nr-of-members = 1
}

pekko.remote.artery {
  transport = tcp
  canonical.hostname = ${PEKKO_REMOTE_HOSTNAME}
  canonical.port = 2551
}

# For reactor/rdbc specifically
org.slf4j.simpleLogger.log.io.r2dbc = "INFO"
org.slf4j.simpleLogger.log.reactor = "INFO"

# Slick Configuration for Projections and Read Side
pekko.projection.slick {
  profile = "slick.jdbc.PostgresProfile$"
  db {
    url = "jdbc:postgresql://"${POSTGRES_HOST}":"${POSTGRES_PORT}"/"${POSTGRES_DB}
    user = ${POSTGRES_USER}
    password = ${POSTGRES_PASSWORD}
    driver = "org.postgresql.Driver"
    numThreads = 10
    maxConnections = 10
    minConnections = 1
  }
}
