include "event-journal.conf"
include "http-server.conf"

http = {
  host = ${HTTP_HOST}
  port = ${HTTP_PORT}
}

pekko {
  actor {
    provider = cluster # Enable actor provisioning through Pekko Cluster
    
    serializers {
      scalapb = "domain.ScalaPbSerializer"
    }
    serialization-bindings {
      "scalapb.GeneratedMessage" = scalapb
    }

    default-dispatcher {
      fork-join-executor {
        parallelism-factor = ${PEKKO_DEFAULT_DISPATCHER_PARALLELISM_FACTOR}
        parallelism-max = ${PEKKO_DEFAULT_DISPATCHER_PARALLELISM_MAX}
      }
      
      throughput = ${PEKKO_DEFAULT_DISPATCHER_THROUGHPUT} # Reduce context switching for cluster / event-handling actors
    }
  }

  # Log level used by the configured loggers (see "loggers") as soon
  # as they have been started; before that, see "stdout-loglevel"
  # Options: OFF, ERROR, WARNING, INFO, DEBUG
  loglevel = ${PEKKO_LOGLEVEL}

  # Loggers to register at boot time (pekko.event.Logging$DefaultLogger logs to STDOUT)
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]

  # Filter of log events that is used by the LoggingAdapter before publishing log events to the eventStream.
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
}


pekko.cluster {
  sharding {
    number-of-shards = ${PEKKO_NUMBER_OF_SHARDS}
  }
  
  # The node joins itself to form a cluster of 1.
  seed-nodes = ["pekko://baseledger@"${PEKKO_REMOTE_HOSTNAME}":"${PEKKO_REMOTE_PORT}]
  
  # Automatically down nodes (irrelevant for a 1-node cluster, but keeps it clean)
  downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  shutdown-after-unsuccessful-join-seed-nodes = 60s
  
  # Start the Shard Region immediately without waiting for other nodes
  min-nr-of-members = 1
}

pekko.remote.artery {
  transport = tcp
  canonical.hostname = ${PEKKO_REMOTE_HOSTNAME}
  canonical.port = ${PEKKO_REMOTE_PORT}
}

# For reactor/rdbc specifically
org.slf4j.simpleLogger.log.io.r2dbc = "INFO"
org.slf4j.simpleLogger.log.reactor = "INFO"


