pekko.persistence.journal.plugin = "pekko.persistence.r2dbc.journal"
pekko.persistence.snapshot-store.plugin = "pekko.persistence.r2dbc.snapshot"
pekko.persistence.state.plugin = "pekko.persistence.r2dbc.state"

pekko.persistence.r2dbc {
  dialect = "postgres"
  connection-factory {
    driver = "postgres"
    host = ${POSTGRES_HOST}
    port = ${POSTGRES_PORT}
    database = ${POSTGRES_DB}
    user = ${POSTGRES_USER}
    password = ${POSTGRES_PASSWORD}

    # Scale the shared R2DBC connection pool (Default is usually 20)
    max-size = ${R2DBC_POOL_MAX_SIZE}
    initial-size = ${R2DBC_POOL_INITIAL_SIZE}
  }
}

