pekko.http {
  server {
    backlog = ${HTTP_SERVER_BACKLOG}
    
    # The maximum number of concurrently accepted TCP connections. 
    # Default is 1024. If this is exceeded, new connections are refused.
    max-connections = ${HTTP_SERVER_MAX_CONNECTIONS}
    
    # The maximum number of concurrent HTTP/2 streams per connection.
    # Increase this if you have clients reuse HTTP/2 connections for high concurrency.
    http2.max-concurrent-streams = ${HTTP_SERVER_HTTP2_MAX_CONCURRENT_STREAMS}

    # The maximum number of requests accepted concurrently on a single HTTP/1.1 connection.
    # Helps clients that use HTTP/1.1 pipelining.
    pipelining-limit = ${HTTP_SERVER_PIPELINING_LIMIT}

    preview {
      enable-http2 = ${HTTP_SERVER_ENABLE_HTTP2}
    }

    use-dispatcher = ${HTTP_SERVER_USE_DISPATCHER}
  }
}

http-dispatcher {
  type = Dispatcher
  executor = "fork-join-executor"
  fork-join-executor {
    # Min threads = CPU cores (usually scales to cores * factor)
    parallelism-min = ${HTTP_DISPATCHER_PARALLELISM_MIN}
    parallelism-factor = ${HTTP_DISPATCHER_PARALLELISM_FACTOR}
    parallelism-max = ${HTTP_DISPATCHER_PARALLELISM_MAX}
  }
  # Number of messages processed by an actor before yielding the thread.
  # The default is 10. Increasing this to 100 reduces context-switching overhead.
  throughput = ${HTTP_DISPATCHER_THROUGHPUT}
}