addSbtPlugin("org.scalameta"         % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.github.sbt"        % "sbt-native-packager" % "1.10.0")
addSbtPlugin("software.purpledragon" % "sbt-dependency-lock" % "1.5.1")
addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix"        % "0.12.1")
addSbtPlugin("com.eed3si9n"          % "sbt-assembly"        % "2.3.0")
